defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

paginate: 10
paginate_path: "/blog/page:num/"

title: Xinwang Liu
subtitle: Professor

# left_side:
#   background_color: "#F00"
#   close_button_color: "#F00"
#   text_color: "#F00"


# Side Menu Links
menu:
  - text: Brief Bio
    link: /
    icon: ""

  - text: Selected Journal Papers
    link: /Selected-Journal-Papers
    icon: ""

  - text: Selected Conference Papers
    link: /Selected-Conference-Papers
    icon: ""
  

# Socialmedia Icons
social_icons:
  - name: google mail
    link: mailto:sihangjoe@gmail.com
    icon: fab fa-google

  - name: github
    link: https://github.com/SihangZhou
    icon: fab fa-github-square


    
